global:
  scrape_interval:     5s
  evaluation_interval: 5s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['0.0.0.0:9090']

  - job_name: 'service-collector'
    static_configs:
      - targets: ['blind-eternities:9000', 'grafana:3000']
