port = 8000
allow_any_localhost_token = true

[db]
host = "localhost"
port = 5432
username = "postgres"
password = "postgres"
name = "blind_eternities"

[playlist_config]
song_dir = "/tmp/blind-eternities-song-dir"
