[package]
name = "common"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
itertools = "0.10.3"
once_cell = "1.9.0"
regex = "1.5.4"
serde = { version = "1.0.136", features = ["derive"] }
serde_json = "1.0.79"
chrono = { version = "0.4.19", features = ["serde"] }
url = "2.2.2"
thiserror = "1.0.30"
tracing = "0.1.31"
tracing-subscriber = "0.3.9"
tracing-log = "0.1.2"
tracing-bunyan-formatter = "0.3.2"
petgraph = "0.6.0"
tokio = { version = "1.17.0", default-features = false }
async-trait = "0.1"
uuid = "1"
whoami = "1.2.3"

[dependencies.sqlx]
version = "0.5.11"
default-features = false
features = [
    "runtime-actix-rustls",
    "macros",
    "uuid",
    "chrono",
    "migrate"
]

[dependencies.reqwest]
version = "0.11.9"
default-features = false
features = ["json", "rustls-tls"]

[dev-dependencies]
fake = "2.4.3"
proptest = "1.0.0"
rand = "0.8.5"

[features]
