[package]
name = "common"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
async-trait = "0.1"
chrono = { version = "0.4.19", features = ["serde"] }
either = "1.9.0"
itertools.workspace = true
once_cell.workspace = true
petgraph = "0.6.0"
regex.workspace = true
serde = { version = "1.0.136", features = ["derive"] }
serde_json = "1.0.79"
thiserror.workspace = true
tokio.workspace = true
tracing.workspace = true
tracing-bunyan-formatter.workspace = true
tracing-log.workspace = true
tracing-subscriber.workspace = true
url = "2.2.2"
uuid.workspace = true
whoami.workspace = true

[dependencies.sqlx]
workspace = true
default-features = false
features = [
    "runtime-actix-rustls",
    "macros",
    "uuid",
    "chrono",
    "migrate"
]

[dependencies.reqwest]
version = "0.11.9"
default-features = false
features = ["json", "rustls-tls"]

[dev-dependencies]
fake = "2.4.3"
proptest = "1.0.0"
rand = "0.8.5"

[features]
